### ISSUE TITLE
Can I upgrade other Bootloader image by this uboot?

### ISSUE THREAD

**Issue by Hallsong** [DragonBluep/uboot-mt7621#1]
Can I upgrade other Bootloader image by this uboot?

**Comment by DragonBluep** [comment]
yes of course.

**Comment by Hallsong** [comment]
I do not know how to do that.
After I select the PB-Boot image and press "upload".
好吧我英文不好，之后就会报错，不管是kernel的bin，还是其他Bootloader文件，均报错。已经砖了。
不知道能不能用ttl操作

**Comment by DragonBluep** [comment]
可以 ttl 刷的，你的设备如果是 NAND Flash，只能上传 initramfs 或者 factory 镜像进行刷机。
当然前提是你在制作 u-boot 的时候选对了 Flash 类型 和内存之类的参数。

**Comment by lovejoy** [comment]
> 可以 ttl 刷的，你的设备如果是 NAND Flash，只能上传 initramfs 或者 factory 镜像进行刷机。 当然前提是你在制作 u-boot 的时候选对了 Flash 类型 和内存之类的参数。

如果用了这个uboot刷了immortalwrt之后怎么刷回breed ？

**Comment by DragonBluep** [comment]
> > 可以 ttl 刷的，你的设备如果是 NAND Flash，只能上传 initramfs 或者 factory 镜像进行刷机。 当然前提是你在制作 u-boot 的时候选对了 Flash 类型 和内存之类的参数。
> 
> 如果用了这个uboot刷了immortalwrt之后怎么刷回breed ？

使用 `mtd` 命令。
