### ISSUE TITLE
is the command sf works fine?

### ISSUE THREAD

**Issue by yunhai20082008** [DragonBluep/uboot-mt7621#10]
I try to run sf 0x3fff000 0xff0000 0x100
as what i know 
0x3fff000 should be ram address
0xff0000 should be flash offset 
0x100 should be the length read from flash to ram
but compare before to after the command:
the result of md.b read 0x3fff000 0x100 are same
Is it an issue?

**Comment by yunhai20082008** [comment]
i tried md.b and mw.b, it seems work fine

**Comment by DragonBluep** [comment]
As far as I can tell, your command format is not correct. And the memory address starts from 0x80000000. You can take a look at this file.
https://github.com/DragonBluep/uboot-mt7621/blob/e55d1401366406435ab40c34885b86a902850077/cmd/sf.c#L598-L618

**Comment by yunhai20082008** [comment]
This problem is solved by using the ram address 0x80000000,thanks
