### ISSUE TITLE
想请教一下，是否对固件大小有限制

### ISSUE THREAD

**Issue by zcy85611** [DragonBluep/uboot-mt7621#4]
我ZTE E8820s用的最新的源码编译的128m的nand flash的uboot，内存是256m，刷小于30m的factory固件可以正常刷入，但是刷46m左右的就会直接提示upgrade failed，请问是我的方法不对，还是确实有固件大小的限制？用专用的breed，可以刷任意大小的固件。

**Comment by DragonBluep** [comment]
可能出现坏块了？

**Comment by zcy85611** [comment]
> 可能出现坏块了？

确定没有坏块，启动的时候的日志显示的是0坏块

**Comment by DragonBluep** [comment]
我刚刚在 RAISECOM MSG1500 上试了下，可以写入 60 M 左右的文件的，没有 TTL 日志不是很好分析问题所在。
```
Web failsafe UI started
GET /
GET /style.css
GET /favicon.ico
POST /upload
    Content-Length: 64889300
GET /style.css
POST /flashing
    Content-Length: 44
GET /style.css
GET /result

Erasing from 0x180000 to 0x3f7ffff, size 0x3e00000 ... OK
Writting from 0x800100a6 to 0x180000, size 0x3de2100 ... OK

*** Firmware upgrade completed! ***

```

**Comment by DragonBluep** [comment]
对了你要是用的火狐浏览器可以换成 chromium 类的试一下。

**Comment by zcy85611** [comment]
> 我刚刚在 RAISECOM MSG1500 上试了下，可以写入 60 M 左右的文件的，没有 TTL 日志不是很好分析问题所在。
> 
> ```
> Web failsafe UI started
> GET /
> GET /style.css
> GET /favicon.ico
> POST /upload
>     Content-Length: 64889300
> GET /style.css
> POST /flashing
>     Content-Length: 44
> GET /style.css
> GET /result
> 
> Erasing from 0x180000 to 0x3f7ffff, size 0x3e00000 ... OK
> Writting from 0x800100a6 to 0x180000, size 0x3de2100 ... OK
> 
> *** Firmware upgrade completed! ***
> ```

msg1500我也有，我找出来试试看，谢谢快速的回复，我是用的edge，应该没问题

**Comment by zcy85611** [comment]
检查过了，确实是坏块的原因，请问未来是否考虑会在刷机的时候自动处理坏块？谢谢

**Comment by DragonBluep** [comment]
不打算了搞了，现在流行另一种 NMBM 坏块处理了，OpenWrt 支持这种模式的。传统的 RAW 刷写模式不太有动力去折腾了，跳过坏块可能也会使系统无法启动的，需要坏块表支持，但是各个机型的情况貌似并不一致。NAND 机型刷机最好是从内存启动 initramfs 再进行系统升级。
