### ISSUE TITLE
Is there any methods to reset or init gpios

### ISSUE THREAD

**Issue by yunhai20082008** [DragonBluep/uboot-mt7621#8]
Hi，there. sorry for my English.
the common gpio is 19,it seems to be resetted after the firmware loaded controlled by the code of firewarm.
I need to reset or init pcie -reset-gpios like 19 24 25. before the firmware loaded.but I didnt find any way in the u-boot code

**Comment by DragonBluep** [comment]
@yunhai20082008 Please refer to this commit. https://github.com/DragonBluep/uboot-mt7621/commit/686b6abf160cc4eae6202c75f9af857bcec547ea

However, all gpios should be controlled by the firmware. This is the correct way.
