### ISSUE TITLE
May I get some programming advices about how to abortboot by network?

### ISSUE THREAD

**Issue by yunhai20082008** [DragonBluep/uboot-mt7621#9]
Sorry for my English.
For this target，I have done：

1. common/autoboot.c
```
static int abortboot(int bootdelay)
{
	int abort = 0;
	/*
	 * If 192.168.1.2 exist,stop autoboot
	 */
	int a=run_command("ping 192.168.1.2", 0);
	printf("a = %d\n", a);
	if (a == 1) {
		if (bootdelay >= 0)
			abort = __abortboot(bootdelay);
	}
	else {
		abort = 1;
		run_command("httpd", 0);
	}
	printf("abort = %d\n", abort);
#ifdef CONFIG_SILENT_CONSOLE
```
2. net/arp.c
```
#ifndef	CONFIG_NET_RETRY_COUNT
# define ARP_TIMEOUT_COUNT	5	/* # of timeouts before giving up  */
#else
# define ARP_TIMEOUT_COUNT	CONFIG_NET_RETRY_COUNT
#endif

# define ARP_TIMEOUT		5000UL
# define ARP_TIMEOUT_COUNT	3
```
一、It wokes fine，but I dont want to change arp.c to decrease the whole time of arp-timeout ,is there any function could be programming into autoboot.c let the function ping run for a fixed time？
二、A better way for abortbooting is reciving a text by tcp or udp,could I get some advices how to make it？Do I need to find a library file like tcp.c?
三、What I need alway helps not issues,Is it suitable write here and is there a more suitable way for it?

**Comment by DragonBluep** [comment]
Perhaps you can take a look at the GPL code of Netgear u-boot, I remember it has similar implementation as you want.

**Comment by yunhai20082008** [comment]
thanks
